# This workflow build and upload a development package to test.pypi.org
# The version is postfixed witf .devYYYYMMDDHHMM, allowing to upload each minute.
# This workflow is run each dày at 23:59, or on demand.

name: Upload Python Package to test.pypi.org

on:
  workflow_dispatch:
  schedule:
    - cron: '59 23 * * *'

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    - name: build dev version
      run: sed -i "s/\"$/.dev$(date +%Y%m%d%H%M)\"/" motioneye/__init__.py
    - name: Build package
      run: python -m build
    - name: Publish package
      run: twine  upload --repository testpypi -u __token__ -p ${{ secrets.TEST_PYPI_API_TOKEN }} dist/* 
      
