# This workflow build and upload a development package to test.pypi.org
# The version is postfixed witf .devYYYYMMDDHHMM, allowing to upload each minute.
# This workflow is run each dày at 23:59, or on demand.
# When run on schedule, a new package is generated only if latest commit is less than 1 day.

name: Upload Python Package

on:
  workflow_dispatch:
  schedule:
    - cron: '59 23 * * *'

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest
    env:
      should_run: true

    steps:
    - uses: actions/checkout@v3
    - name: print latest_commit
      run: echo ${{ github.sha }}
    - name: check latest commit is less than a day
      if: ${{ github.event_name == 'schedule' }}
      run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "should_run=false" >> $GITHUB_ENV ; true
    - name: Set up Python
      if: ${{ env.should_run != 'false' }}
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      if: ${{ env.should_run != 'false' }}
      run: |
        python3 -m pip install --upgrade pip
        pip3 install build twine
    - name: build dev version
      if: ${{ env.should_run != 'false' }}
      run: sed -i "s/\"$/.dev$(date +%Y%m%d%H%M)\"/" motioneye/__init__.py
    - name: Build and publish package
      if: ${{ env.should_run != 'false' }}
      run: |
        python3 -m build
        twine upload --repository testpypi -u __token__ -p ${{ secrets.TEST_PYPI_API_TOKEN }} dist/*
      
